spring.application.name=Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/finos_ai
spring.datasource.username=postgres
spring.datasource.password=Raghav5911

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true